apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo
  namespace: argocd
spec:
  project: app-stack
  source:
    repoURL: https://github.com/Thepowerfulmark/k3s-gitops-platform.git
    targetRevision: main
    path: charts/app-stack
    helm:
      releaseName: demo
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
