apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: app-stack
  namespace: argocd
spec:
  description: Application stack from this template
  sourceRepos:
    - https://github.com/Thepowerfulmark/k3s-gitops-platform.git
    - https://github.com/Thepowerfulmark/k3s-gitops-platform
  destinations:
    - namespace: demo
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
